import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { DCFInputs } from "./dcf";
import type { DCFResult } from "./dcf";
import { formatCurrency, formatNumber, formatPercent, formatMillions } from "./formatters";

export const exportPDF = (inputs: DCFInputs, result: DCFResult) => {
  const doc = new jsPDF();
  const date = new Date().toLocaleDateString();

  doc.setFontSize(18);
  doc.text("DCF Valuation Report", 14, 18);
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(`${inputs.companyName} • ${inputs.industry} • ${date}`, 14, 25);
  doc.setTextColor(0);

  autoTable(doc, {
    startY: 32,
    head: [["Key Metric", "Value"]],
    body: [
      ["Intrinsic Value / Share", formatCurrency(result.intrinsicValuePerShare)],
      ["Current Market Price", formatCurrency(inputs.currentPrice)],
      ["Upside / Downside", formatPercent(result.upsideDownside)],
      ["Verdict", result.verdict.replace("_", " ")],
    ],
    styles: { font: "courier", fontSize: 10 },
    headStyles: { fillColor: [10, 10, 10] },
  });

  autoTable(doc, {
    head: [["Input", "Value"]],
    body: [
      ["Base FCF (€M)", formatNumber(inputs.baseFCF, 0)],
      ["FCF Growth (%)", formatPercent(inputs.fcfGrowthRate)],
      ["WACC (%)", formatPercent(inputs.wacc)],
      ["Terminal Growth (%)", formatPercent(inputs.terminalGrowthRate)],
      ["Net Debt (€M)", formatNumber(inputs.netDebt, 0)],
      ["Shares Outstanding (M)", formatNumber(inputs.sharesOutstanding, 0)],
      ["Convention", inputs.useMidYear ? "Mid-year" : "End-of-year"],
    ],
    styles: { font: "courier", fontSize: 10 },
    headStyles: { fillColor: [10, 10, 10] },
  });

  autoTable(doc, {
    head: [["Year", "FCF (€M)", "Discount Factor", "PV of FCF (€M)"]],
    body: [
      ...result.rows.map((r) => [
        String(r.year),
        formatNumber(r.fcf, 0),
        formatNumber(r.discountFactor, 4),
        formatNumber(r.pvFCF, 0),
      ]),
      ["TV", "", "", formatNumber(result.pvTerminalValue, 0)],
      ["EV", "", "", formatNumber(result.enterpriseValue, 0)],
    ],
    styles: { font: "courier", fontSize: 10 },
    headStyles: { fillColor: [10, 10, 10] },
  });

  autoTable(doc, {
    head: [["Summary", "Value"]],
    body: [
      ["Sum of PV (Y1–5)", formatMillions(result.sumPV)],
      ["Terminal Value", formatMillions(result.terminalValue)],
      ["PV of Terminal Value", formatMillions(result.pvTerminalValue)],
      ["Enterprise Value", formatMillions(result.enterpriseValue)],
      ["Net Debt", formatMillions(result.netDebt)],
      ["Equity Value", formatMillions(result.equityValue)],
    ],
    styles: { font: "courier", fontSize: 10 },
    headStyles: { fillColor: [10, 10, 10] },
  });

  const pageH = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text("Generated by DCF Valuation Tool. For informational purposes only.", 14, pageH - 8);

  doc.save(`DCF_${inputs.companyName.replace(/\s+/g, "_")}.pdf`);
};

export const exportResultsToClipboard = async (inputs: DCFInputs, result: DCFResult) => {
  const lines = [
    `DCF Valuation — ${inputs.companyName}`,
    `Intrinsic Value/Share: ${formatCurrency(result.intrinsicValuePerShare)}`,
    `Current Price: ${formatCurrency(inputs.currentPrice)}`,
    `Upside/Downside: ${formatPercent(result.upsideDownside)}`,
    `Verdict: ${result.verdict.replace("_", " ")}`,
    `Enterprise Value: ${formatMillions(result.enterpriseValue)}`,
    `Equity Value: ${formatMillions(result.equityValue)}`,
    `WACC: ${formatPercent(inputs.wacc)} • TGR: ${formatPercent(inputs.terminalGrowthRate)}`,
  ].join("\n");
  await navigator.clipboard.writeText(lines);
};
